# Hugo Site Configuration
# Template for Masjid Ikhlas V3 - Customize for your organization

baseURL = "https://inayet.github.io/masjidikhlas-v3/"
languageCode = 'en-us'
title = 'Masjid Ikhlas'
theme = 'ikhlas'

[params]
  # Organization Information
  description = "Metropolitan Denver North Islamic Center - Masjid Ikhlas is committed to Islamic way of life based on Qur'an and life example of Prophet Muhammad (Peace be upon him)"
  author = "Masjid Ikhlas"
  logo = "/images/logo.png"
  
  # Contact Information
  contact_email = "office@masjidikhlas.org"
  phone = "303-920-0252"
  address = "11141 N Irma Drive, Northglenn, CO 80233, USA"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Main Navigation Menu
# Customize these menu items for your masjid's structure
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 20

  [[menu.main]]
    name = "Prayer Schedule"
    url = "/monthly-prayer-schedule/"
    weight = 30

  [[menu.main]]
    name = "Programs"
    url = "/services/"
    weight = 40

  [[menu.main]]
    name = "Education"
    url = "/ikhlas-academy/"
    weight = 45

  [[menu.main]]
    name = "Youth"
    url = "/ikhlas-youth-department/"
    weight = 47

  [[menu.main]]
    name = "Outreach"
    url = "/outreach-department/"
    weight = 48

  [[menu.main]]
    name = "Donate"
    url = "/donate/"
    weight = 50

  [[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 60

# Social Media Links
# Replace with your masjid's social media accounts
[social]
  facebook = "https://facebook.com/yourmasjid"
  instagram = "https://instagram.com/yourmasjid"
  twitter = "https://twitter.com/yourmasjid"
  youtube = "https://youtube.com/channel/UC8tPOcewvQp80xQWSsUgauQ"